name: publish package

on: workflow_dispatch

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Obtain NativeLibs
        run: |
          curl -1 -O 'https://dl.cloudsmith.io/public/vignette/vg-prebuiltlibs/raw/names/vignette.NativeLibs/versions/2020.1027.0/vignette.NativeLibs.zip'
          unzip vignette.NativeLibs.zip

      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Cake Build Script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: Build

      - name: Determine Version
        uses: pCYSl5EDgo/cat@master
        id: build_version
        with:
          path: ./artifacts/version

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifacts/

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.build_version.outputs.text }}
          files: artifacts/*.nupkg

      - name: Publish to NuGet
        run:  |
           dotnet nuget push ./artifacts/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true && \
           dotnet tool install gpr -g && \
           gpr push ./artifacts/*.nupkg --repository https://github.com/${{github.repository}} -k ${{github.token}}
